-- SILVA VISION V0.5 MEGA BLOCK 23
-- Visual Composer — CLIENT ONLY / STATE ONLY.
-- Consolida cena, solar, clima, água, emergência, exposição, balanço e governor.

local Composer={enabled=true,interval=250,state={quality=1.0,night=0.0,wet=0.0,storm=0.0,fog=0.0,street=0.0,reflection=0.0,atmosphere=0.0,cinematic=0.0,sunrise=0.0,day=1.0,golden=0.0,sunset=0.0,solar=1.0,emergency=0.0,exposure=1.0,balance=1.0,lightWeight=1.0,rainWeight=1.0}}
local function clamp(v,a,b)return math.max(a,math.min(b,v))end
local function call(name,...)
 local ok,r=pcall(function()return exports['silva-vision-core'][name](...)end);return ok and r or nil
end
local function smooth(o,t,k)return o+(t-o)*k end
local function update()
 if not Composer.enabled then return end
 local s=call('GetVisualSceneState') or {};local wb=call('GetVisualWeatherBlendState') or {};local sun=call('GetVisualSunCycleState') or {};local e=call('GetVisualEmergencySceneState') or {};local b=call('GetVisualBudget') or {};local water=call('GetVisualReflectionDirectorState') or call('GetWaterReflectionState') or {};local ex=call('GetVisualExposureGuardState') or {};local lb=call('GetVisualLightingBalanceState') or {};local gov=call('GetVisualLightGovernorState') or {}
 local q=clamp(tonumber(b.multiplier) or 1,0.72,1);local night=clamp(tonumber(sun.night) or tonumber(s.night) or 0,0,1);local wet=clamp(tonumber(wb.wet) or tonumber(s.wet) or 0,0,1);local storm=clamp(tonumber(wb.storm) or tonumber(s.storm) or 0,0,1);local fog=clamp(tonumber(wb.fog) or tonumber(s.fog) or 0,0,1);local street=clamp(math.max(tonumber(sun.street) or 0,tonumber(s.streetDemand) or 0,tonumber(gov.street) or 0),0,1);local reflection=clamp(math.max(tonumber(s.reflectionDemand) or 0,tonumber(water.reflection) or 0),0,1);local atmosphere=clamp(tonumber(s.atmosphereDemand) or 0,0,1);local cinematic=clamp(math.max(tonumber(s.cinematic) or 0,tonumber(sun.golden) or 0),0,1);local emergency=clamp(tonumber(e.active) or tonumber(s.emergency) or 0,0,1)
 Composer.state.night=smooth(Composer.state.night,night,0.16);Composer.state.wet=smooth(Composer.state.wet,wet,0.14);Composer.state.storm=smooth(Composer.state.storm,storm,0.16);Composer.state.fog=smooth(Composer.state.fog,fog,0.12);Composer.state.street=smooth(Composer.state.street,street,0.16);Composer.state.reflection=smooth(Composer.state.reflection,reflection,0.14);Composer.state.atmosphere=smooth(Composer.state.atmosphere,atmosphere,0.12);Composer.state.cinematic=smooth(Composer.state.cinematic,cinematic,0.10);Composer.state.sunrise=tonumber(sun.sunrise) or 0;Composer.state.day=tonumber(sun.day) or 1;Composer.state.golden=tonumber(sun.golden) or 0;Composer.state.sunset=tonumber(sun.sunset) or 0;Composer.state.solar=tonumber(sun.solar) or 1;Composer.state.emergency=smooth(Composer.state.emergency,emergency,0.18);Composer.state.exposure=smooth(Composer.state.exposure,clamp(tonumber(ex.factor) or 1,0.88,1.04),0.14);Composer.state.balance=smooth(Composer.state.balance,clamp(tonumber(lb.balance) or 1,0.90,1.04),0.14)
 Composer.state.quality=q;Composer.state.lightWeight=clamp(q*(1+Composer.state.street*0.10+Composer.state.night*0.08+Composer.state.emergency*0.04)*Composer.state.balance*Composer.state.exposure,0.72,1);Composer.state.rainWeight=clamp(q*(1+Composer.state.wet*0.08+Composer.state.storm*0.06),0.72,1)
end
CreateThread(function()Wait(10500);while true do update();Wait(Composer.interval)end end)
RegisterCommand('svcomposer',function(_,a)if a[1]=='on'then Composer.enabled=true elseif a[1]=='off'then Composer.enabled=false elseif a[1]=='reapply'then update() elseif a[1]=='show'or not a[1]then local s=Composer.state;print(('[SilvaVision] composer q=%.2f solar=%.2f night=%.2f wet=%.2f storm=%.2f street=%.2f refl=%.2f em=%.2f exposure=%.2f balance=%.2f'):format(s.quality,s.solar,s.night,s.wet,s.storm,s.street,s.reflection,s.emergency,s.exposure,s.balance));return else print('[SilvaVision] svcomposer on | off | reapply | show');return end;print('[SilvaVision] Composer '..(Composer.enabled and 'ON' or 'OFF'))end,false)
exports('GetVisualComposerState',function()return Composer.state end)
